config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :users
  root to: "maps#index"
  resources :maps, only: [:index, :show] do
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:create]
      member do
        get 'search'
      end
    end
  end

  resources :users  , only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ActiveHash::Base

  self.data = [
    { id: 1, name: '岩沼市' },
    { id: 2, name: '多賀城市' },
    { id: 3, name: '塩釜市' },
    { id: 4, name: '七ヶ浜町' },
    { id: 5, name: '利府町' },
    { id: 6, name: '松島町' },
    { id: 7, name: '大郷町' },
    { id: 8, name: '大衡村' },
    { id: 9, name: '富谷市' },
    { id: 10, name: '大和町' },
    { id: 11, name: '登米市' },
    { id: 12, name: '栗原市' },
    { id: 13, name: '加美町' },
    { id: 14, name: '色麻町' },
    { id: 15, name: '大崎市' },
    { id: 16, name: '美里町' },
    { id: 17, name: '涌谷町' },
    { id: 18, name: '東松島市' },
    { id: 19, name: '石巻市' },
    { id: 20, name: '女川町' },
    { id: 21, name: '南三陸町' },
    { id: 22, name: '気仙沼市' },
    { id: 23, name: '大河原町' },
    { id: 24, name: '柴田町' },
    { id: 25, name: '村田町' },
    { id: 26, name: '蔵王町' },
    { id: 27, name: '川崎町' },
    { id: 28, name: '角田市' },
    { id: 29, name: '七ヶ宿町' },
    { id: 30, name: '白石市' },
    { id: 31, name: '丸森町' },
    { id: 32, name: '仙台市青葉区' },
    { id: 33, name: '仙台市泉区' },
    { id: 34, name: '仙台市宮城野区' },
    { id: 35, name: '仙台市太白区' },
    { id: 36, name: '仙台市若林区' },
    { id: 37, name: '名取市' },
    { id: 38, name: '亘理町' },
    { id: 39, name: '山元町' }
  ]

  include ActiveHash::Associations
  has_many :citys

  end

app/models/comment.rb
class Comment < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :city
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :city
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

with_options presence: true do

  validates :image
  validates :title
  validates :about
  
end

def self.search(search)
  if search != ""
    Post.where('title LIKE(?)', "%#{search}%")
  else
    Post.all
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do

    validates :nickname
    validates :birthday
    
  end

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to map_post_path(@comment.city, @comment.post)
    else
      redirect_to map_post_path(@comment.city, @comment.post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, city_id: params[:map_id], post_id: params[:post_id])
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
  end

  def show
    @city = City.find(params[:id])
    @post = Post.where(city_id: params[:id]).order("created_at DESC")
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_city, only: [:new, :create, :show, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :comfirmation, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to map_path(@city)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to map_post_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to map_path(@post.city.id)
    else
      redirect_to root_path
    end
  end

  def search
    @post = Post.search(params[:key])
  end

  private

  def post_params
    params.require(:post).permit(:image, :title, :about, :day, :town, :number, :building).merge(user_id: current_user.id, city_id: params[:map_id])
  end

  def set_city
    @city = City.find(params[:map_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def comfirmation
    redirect_to root_path unless current_user == @post.user
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @post = @user.posts.order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shascene</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>

    <header class="header">
      <div class="inner">

        <div class="nav">

          <div class="logo">
            <%= link_to 'Shascene', root_path, class: :title_logo %>
          </div>

          <% if user_signed_in? %>
            <div class="nav_right">
              <%= link_to "#{current_user.nickname}", user_path(current_user), class: :user_name %>
               <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: :nav__btn %>
             </div>
             <% else %>
            <div class="nav_right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
           <% end %>

        </div>

      </div>
    </header>

    <%= yield %>

    <footer class="footer">
      <p class="copyright">Copyright © shascene All rights reserved.</p>
    </footer>

  </body>
</html>

app/views/maps/index.html.erb
<div class='title-contents'>
    <h2 class='service-title'>
      あの景色を想い出そう
    </h2>
    <p class='service-explain'>
      Shasceneで想い出の景色を共有
    </p>
    <p class='service-explain'>
      想い出投稿アプリ
    </p>
</div>

<%# aboutボックス %>
     <div class="info">
                <p class=about>ABOUT SERVICE</p>

                <div class=into_info>
                <p>2011.3.11 東日本大震災は多くのものを奪っていきました。 </p>
                <p>生活していた、遊んでいた景色を想い出ごと攫っていきました。 </p>
                <p>あなたが持っている何気ない写真を投稿してください。 </p>
                <p>その写真を見ることで救われる大切な想いがあるはずです。 </p>
               </div>
      </div>

            <%# 宮城県地図 %>
   <div class="map">

   <p  class="prefecture">宮城県</p>
     <%= image_tag "miyagi-map.png", name: "miyagimap", width: "700", height: "620", border: "0", id: "miyagimap", usemap: "#m_miyagimap", alt: "宮城県の市町村マップの画像" %>

           <%# 地図の座標指定 %>
    <map name="m_miyagimap" id="m_miyagimap">
       <area shape="rect" coords="283,440,319,452" href="/maps/1" alt="">
       <area shape="rect" coords="369,388,417,400" href="/maps/2" alt="">
       <area shape="rect" coords="403,343,439,355" href="/maps/3" alt="">
       <area shape="rect" coords="405,366,454,378" href="/maps/4" alt="">
       <area shape="rect" coords="327,317,363,329" href="/maps/5" alt="">
       <area shape="rect" coords="362,295,398,307" href="/maps/6" alt="">
       <area shape="rect" coords="334,281,370,293" href="/maps/7" alt="">
       <area shape="rect" coords="280,257,316,269" href="/maps/8" alt="">
       <area shape="rect" coords="293,305,329,317" href="/maps/9" alt="">
       <area shape="rect" coords="252,278,288,290" href="/maps/10" alt="">
       <area shape="rect" coords="432,160,468,172" href="/maps/11" alt="">
       <area shape="rect" coords="311,101,347,113" href="/maps/12" alt="">
       <area shape="rect" coords="216,197,252,209" href="/maps/13" alt="">
       <area shape="rect" coords="249,234,286,246" href="/maps/14" alt="">
       <area shape="rect" coords="309,202,345,214" href="/maps/15" alt="">
       <area shape="rect" coords="383,242,419,254" href="/maps/16" alt="">
       <area shape="rect" coords="393,219,429,231" href="/maps/17" alt="">
       <area shape="rect" coords="404,294,452,306" href="/maps/18" alt="">
       <area shape="rect" coords="464,243,500,255" href="/maps/19" alt="">
       <area shape="rect" coords="517,273,553,285" href="/maps/20" alt="">
       <area shape="rect" coords="514,159,562,171" href="/maps/21" alt="">
       <area shape="rect" coords="532,69,581,81" href="/maps/22" alt="">
       <area shape="rect" coords="218,469,266,481" href="/maps/23" alt="">
       <area shape="rect" coords="248,452,284,464" href="/maps/24" alt="">
       <area shape="rect" coords="224,434,260,446" href="m/maps/25" alt="">
       <area shape="rect" coords="167,438,203,450" href="/maps/26" alt="">
       <area shape="rect" coords="164,394,200,406" href="/maps/27" alt="">
       <area shape="rect" coords="242,497,278,509" href="/maps/28" alt="">
       <area shape="rect" coords="90,481,138,493" href="/maps/29" alt="">
       <area shape="rect" coords="172,496,207,508" href="/maps/30" alt="">
       <area shape="rect" coords="236,556,272,568" href="/maps/31" alt="">
       <area shape="rect" coords="201,328,237,340" href="/maps/32" alt="">
       <area shape="rect" coords="263,325,287,337" href="/maps/33" alt="">
       <area shape="rect" coords="308,360,355,372" href="/maps/34" alt="">
       <area shape="rect" coords="229,378,265,390" href="/maps/35" alt="">
       <area shape="rect" coords="312,383,348,395" href="/maps/36" alt="">
       <area shape="rect" coords="281,412,317,424" href="/maps/37" alt="">
       <area shape="rect" coords="280,473,316,485" href="/maps/38" alt="">
       <area shape="rect" coords="290,519,325,531" href="/maps/39" alt="">
    </map>

  </div>
  
  </div>

app/views/maps/show.html.erb
<div class="city">
<%= @city.name %>
</div>

    <%# 投稿検索 %>
   <div >
     <%= form_with(url: search_map_post_path(@post), local: true, method: :get, class: "search-form") do |form| %>
     <%= form.text_field :key, placeholder: "投稿を検索する", class: "search-input" %>
     <%= form.submit "検索", class: "search-btn" %>
     <% end %>
   </div>

     <%# 投稿一覧 %>
    <div class='post-contents'>
    <ul class='post-lists'>

      <% @post.each do |post| %>
      <li class='list'>
      <%= link_to map_post_path(@city, post) do %>
        <div class='post-img-content'>
        <%= image_tag post.image, class: "post-img" %>
        </div>

        <div class='post-info'>

          <h3 class='post-name'>
          <%= post.title %>
          </h3>
          <div class='post-day'>
          <%= post.day %>
          </div>

        </div>
        <% end %>
      </li>
      <% end %>

      </ul>
      </div>
    <%# 投稿一覧 %>

    <%# 投稿ががない場合の表示 %>
      <% if @post.length == 0 %>
      <div class='nopost'>
          <h3 class='city'>
            想い出の場所を<br>投稿してください
          </h3>
        </div>
        <%# <%= image_tag "noimg.png", class: "item-img" %> 
      <% end %>
     <%# /投稿がない場合の表示 %>


    <%# 投稿ボタン %>
<%= link_to(new_map_post_path(@city), class: 'purchase-btn') do %>
<span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/posts/_form.html.erb
<%# クリエイトフォーム %>
<%= form_with(model: post, url: map_posts_path, method: :post, class: 'registration-main', local: true )do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      新規投稿
    </h1>
  </div>

  <%# エラー文の表示 %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
   <div class='form-text-wrap'>
    <%= f.label :image, "想い出の画像", class: 'form-text' %><br />
    <span class="indispensable">必須</span>
   </div>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
    <%= f.label :title, "想い出の名称", class: 'form-text' %><br />
    <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
    <%= f.label :about, "想い出について",class: 'form-text' %><br />
    <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :about %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">撮影日</label>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        f.date_select(
        :day,
        class:'form-text',
        id:"birth-date",
        use_month_numbers: true,
        prompt:'--',
        start_year: 1930,
        end_year: (Time.now.year),
        date_separator: '%s'),
       "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %> 
    </div>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :town, "町名",class: 'form-text' %><br />
    </div>
    <%= f.text_field :town %>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :number, "番地",class: 'form-text' %><br />
    </div>
    <%= f.text_field :number %>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :building, "建物名",class: 'form-text' %><br />
    </div>
    <%= f.text_field :building %>
  </div>

  <div class="form-group">
    <div class="register-btn">
    <%= f.submit "投稿する", class:"register-red-btn" %>
    </div>
  </div>

  </div>

<% end %>

app/views/posts/_forme.html.erb
<%# アップデートフォーム %>
<%= form_with(model: post, url: map_post_path, method: :patch , class: 'registration-main', local: true )do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      投稿編集
    </h1>
  </div>

  <%# エラー文の表示 %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
   <div class='form-text-wrap'>
    <%= f.label :image, "想い出の画像", class: 'form-text' %><br />
    <span class="indispensable">必須</span>
   </div>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
    <%= f.label :title, "想い出の名称", class: 'form-text' %><br />
    <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
    <%= f.label :about, "想い出について",class: 'form-text' %><br />
    <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :about %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">撮影日</label>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        f.date_select(
        :day,
        class:'form-text',
        id:"birth-date",
        use_month_numbers: true,
        prompt:'--',
        start_year: 1930,
        end_year: (Time.now.year),
        date_separator: '%s'),
       "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %> 
    </div>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :town, "町名",class: 'form-text' %><br />
    </div>
    <%= f.text_field :town %>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :number, "番地",class: 'form-text' %><br />
    </div>
    <%= f.text_field :number %>
  </div>

  <div class="form-group">
  <div class='form-text-wrap'>
    <%= f.label :building, "建物名",class: 'form-text' %><br />
    </div>
    <%= f.text_field :building %>
  </div>

  <div class="form-group">
    <div class="register-btn">
    <%= f.submit "更新する", class:"register-red-btn" %>
    </div>
  </div>

  </div>

<% end %>

app/views/posts/edit.html.erb
<%= render partial: "forme", locals: { post: @post } %>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: map_posts_path(@city), method: :post, local: true )do |f| %>

  <div class="form-group">
    <%= f.label :image, "思い出の画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :title, "思い出の名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :about, "詳細" %><br />
    <%= f.text_area :about %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">日付</label>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
        f.date_select(
        :day,
        class:'select-birth',
        id:"birth-date",
        use_month_numbers: true,
        prompt:'--',
        start_year: 1930,
        end_year: (Time.now.year - 5),
        date_separator: '%s'),
       "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %> 
    </div>
  </div>

  <div class="form-group">
    <%= f.label :town, "シティ" %><br />
    <%= f.text_field :town %>
  </div>

  <div class="form-group">
    <%= f.label :number, "番地" %><br />
    <%= f.text_field :number %>
  </div>

  <div class="form-group">
    <%= f.label :building, "建物名" %><br />
    <%= f.text_field :building %>
  </div>

  <div class="register-btn">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>

<% end %>

app/views/posts/search.html.erb
<div class="city">
<%= "検索結果" %>
</div>

    <%# 投稿検索 %>
   <div >
     <%= form_with(url: search_map_post_path(@post), local: true, method: :get, class: "search-form") do |form| %>
     <%= form.text_field :key, placeholder: "投稿を検索する", class: "search-input" %>
     <%= form.submit "検索", class: "search-btn" %>
     <% end %>
   </div>

     <%# 投稿一覧 %>
    <div class='post-contents'>
    <ul class='post-lists'>

      <% @post.each do |post| %>
      <li class='list'>
      <%= link_to map_post_path(post.city_id,post.id) do %>
        <div class='post-img-content'>
        <%= image_tag post.image, class: "post-img" %>
        </div>

        <div class='post-info'>

          <h3 class='post-name'>
          <%= post.title %>
          </h3>
          <div class='post-day'>
          <%= post.day %>
          </div>

        </div>
        <% end %>
      </li>
      <% end %>

    </ul>
    </div>

    <%# 投稿ががない場合の表示 %>
      <% if @post.length == 0 %>
      <div class='nopost'>
          <h3 class='city'>
            検索と一致する<br>投稿はありません
          </h3>
        </div>
        <%# <%= image_tag "noimg.png", class: "item-img" %> 
      <% end %>
     <%# /投稿がない場合の表示 %>

app/views/posts/show.html.erb
  <div class="post-show">
    <div class="post-box">

      <h3 class="name">
        <%= @post.title %>
      </h3>
      
      <div class='user-name'>
      <%= link_to "by #{@post.user.nickname}", user_path(@post.user.id), class: "name_user" %>
      </div>

            <%# 編集と削除(投稿ユーザーのみ) %>
      <% if current_user == @post.user%>
        <div class="btn">
          <%= link_to "編集する", edit_map_post_path(@city, @post), class: "post-btn" %>
          <%= link_to "削除する", map_post_path(@city, @post), method: :delete, class:'post-destroy' %>
        </div>
      <% end %>

      <div class="post-img-content">
        <%= image_tag @post.image %>
      </div>

      <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-post">写真について</th>
          <td class="detail-value"><%= @post.about %></td>
        </tr>
        <tr>
          <th class="detail-post">撮影日</th>
          <td class="detail-value"><%= @post.day %></td>
        </tr>
        <tr>
          <th class="detail-post">町名</th>
          <td class="detail-value"><%= @post.town %></td>
        </tr>
        <tr>
          <th class="detail-post">番地</th>
          <td class="detail-value"><%= @post.number %></td>
        </tr>
        <tr>
          <th class="detail-post">建物名</th>
          <td class="detail-value"><%= @post.building %></td>
        </tr>
      </tbody>
    </table>

      <%# コメント %>
      <div class="post__comments">

        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment],url: map_post_comments_path(@city, @post), local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>

        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text%>
              <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>

      </div>

        
    </div>
  </div>

app/views/users/show.html.erb
<div class="inner">
    <div class="user__wrapper">

      <h2 class="page-heading">
        <%= "#{@user.nickname}さんのマイページ"%>
      </h2>

      <table class="table">
        <tbody>

          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>

          <tr>
            <th class="table__col1">誕生日</th>
            <td class="table__col2"><%= @user.birthday %></td>
          </tr>

        </tbody>
      </table>

      <h2 class="city">
        <%= "#{@user.nickname}さんの投稿"%>
      </h2>

       <%# 投稿一覧 %>
      <div class='post--contents'>
       <ul class='post-lists'>

      <% @post.each do |post| %>
      <li class='list'>
      <%= link_to map_post_path(post.city_id,post.id) do %>
        <div class='post-img-content'>
        <%= image_tag post.image, class: "post-img" %>
        </div>

        <div class='post-info'>

          <h3 class='post-name'>
          <%= post.title %>
          </h3>
          <div class='post-day'>
          <%= post.day %>
          </div>

        </div>
        <% end %>
      </li>
      <% end %>

      </ul>
      </div>
    <%# 投稿一覧 %>
    
     </div>
    </div>